Officially drop python 2 support.
No longer works with python 2 since commit 2e43813.

> TypeError: east_asian_width() argument 1 must be unicode, not str